export const STARTOPTIONS = [
  {value : '', name : '시작 시간'},
  { value: '00:00', name: '00:00' },
  { value: '01:00', name: '01:00' },
  { value: '02:00', name: '02:00' },
  { value: '03:00', name: '03:00' },
  { value: '04:00', name: '04:00' },
  { value: '05:00', name: '05:00' },
  { value: '06:00', name: '06:00' },
  { value: '07:00', name: '07:00' },
  { value: '08:00', name: '08:00' },
  { value: '09:00', name: '09:00' },
  { value: '10:00', name: '10:00' },
  { value: '11:00', name: '11:00' },
  { value: '12:00', name: '12:00' },
  { value: '13:00', name: '13:00' },
  { value: '14:00', name: '14:00' },
  { value: '15:00', name: '15:00' },
  { value: '16:00', name: '16:00' },
  { value: '17:00', name: '17:00' },
  { value: '18:00', name: '18:00' },
  { value: '19:00', name: '19:00' },
  { value: '20:00', name: '20:00' },
  { value: '21:00', name: '21:00' },
  { value: '22:00', name: '22:00' },
  { value: '23:00', name: '23:00' },
  { value: '24:00', name: '24:00' }
]

export const ENDOPTIONS = [
  {value : '', name : '종료 시간'},
  { value: '00:00', name: '00:00' },
  { value: '01:00', name: '01:00' },
  { value: '02:00', name: '02:00' },
  { value: '03:00', name: '03:00' },
  { value: '04:00', name: '04:00' },
  { value: '05:00', name: '05:00' },
  { value: '06:00', name: '06:00' },
  { value: '07:00', name: '07:00' },
  { value: '08:00', name: '08:00' },
  { value: '09:00', name: '09:00' },
  { value: '10:00', name: '10:00' },
  { value: '11:00', name: '11:00' },
  { value: '12:00', name: '12:00' },
  { value: '13:00', name: '13:00' },
  { value: '14:00', name: '14:00' },
  { value: '15:00', name: '15:00' },
  { value: '16:00', name: '16:00' },
  { value: '17:00', name: '17:00' },
  { value: '18:00', name: '18:00' },
  { value: '19:00', name: '19:00' },
  { value: '20:00', name: '20:00' },
  { value: '21:00', name: '21:00' },
  { value: '22:00', name: '22:00' },
  { value: '23:00', name: '23:00' },
  { value: '24:00', name: '24:00' }
]

export const REGION = [
  { value: '지역', name: '지역 선택' },
  { value: '서울', name: '서울특별시' },
  { value: '부산', name: '부산광역시' },
  { value: '대구', name: '대구광역시' },
  { value: '인천', name: '인천광역시' },
  { value: '광주', name: '광주광역시' },
  { value: '대전', name: '대전광역시' },
  { value: '울산', name: '울산광역시' },
  { value: '경기', name: '경기도' },
  { value: '강원', name: '강원도' },
  { value: '세종', name: '세종특별자치시' },
  { value: '충북', name: '충청북도' },
  { value: '충남', name: '충청남도' },
  { value: '전북', name: '전라북도' },
  { value: '전남', name: '전라남도' },
  { value: '경북', name: '경상북도' },
  { value: '경남', name: '경상남도' },
  { value: '제주', name: '제주도' }
]

export const AREA = [
  {
    id: 1,
    name: '서울',
    list: [
      { value: '시/구/군' },
      { value: '강남구' },
      { value: '강동구' },
      { value: '강북구' },
      { value: '강서구' },
      { value: '관악구' },
      { value: '광진구' },
      { value: '구로구' },
      { value: '금천구' },
      { value: '노원구' },
      { value: '도봉구' },
      { value: '동대문구' },
      { value: '동작구' },
      { value: '마포구' },
      { value: '서대문구' },
      { value: '서초구' },
      { value: '성동구' },
      { value: '성북구' },
      { value: '송파구' },
      { value: '양천구' },
      { value: '영등포구' },
      { value: '용산구' },
      { value: '은평구' },
      { value: '종로구' },
      { value: '중구' },
      { value: '중랑구' }
    ]
  },
  {
    id: 2,
    name: '경기',
    list: [
      { value: '시/구/군' },
      { value: '고양시' },
      { value: '과천시' },
      { value: '광명시' },
      { value: '구리시' },
      { value: '군포시' },
      { value: '남양주시' },
      { value: '동두천시' },
      { value: '부천시' },
      { value: '성남시' },
      { value: '수원시' },
      { value: '시흥시' },
      { value: '안산시' },
      { value: '안양시' },
      { value: '오산시' },
      { value: '의왕시' },
      { value: '의정부시' },
      { value: '평택시' },
      { value: '하남시' },
      { value: '가평군' },
      { value: '광주시' },
      { value: '김포시' },
      { value: '안성시' },
      { value: '양주군' },
      { value: '양평군' },
      { value: '여주군' },
      { value: '연천군' },
      { value: '용인시' },
      { value: '이천군' },
      { value: '파주시' },
      { value: '포천시' },
      { value: '화성시' }
    ]
  },
  {
    id: 3,
    name: '부산',
    list: [
      { value: '시/구/군' },
      { value: '강서구' },
      { value: '금정구' },
      { value: '남구' },
      { value: '동구' },
      { value: '동래구' },
      { value: '부산진구' },
      { value: '북구' },
      { value: '사상구' },
      { value: '사하구' },
      { value: '서구' },
      { value: '수영구' },
      { value: '연제구' },
      { value: '영도구' },
      { value: '중구' },
      { value: '해운대구' },
      { value: '기장군' }
    ]
  },
  {
    id: 4,
    name: '대구',
    list: [
      { value: '시/구/군' },
      { value: '남구' },
      { value: '달서구' },
      { value: '동구' },
      { value: '북구' },
      { value: '서구' },
      { value: '수성구' },
      { value: '중구' },
      { value: '달성군' }
    ]
  },
  {
    id: 5,
    name: '인천',
    list: [
      { value: '시/구/군' },
      { value: '계양구' },
      { value: '남구' },
      { value: '남동구' },
      { value: '동구' },
      { value: '부평구' },
      { value: '서구' },
      { value: '연수구' },
      { value: '중구' },
      { value: '강화군' },
      { value: '옹진군' }
    ]
  },
  {
    id: 6,
    name: '광주',
    list: [
      { value: '광산구' },
      { value: '남구' },
      { value: '동구' },
      { value: '북구' },
      { value: '서구' }
    ]
  },
  {
    id: 7,
    name: '대전',
    list: [
      { value: '시/구/군' },
      { value: '대덕구' },
      { value: '동구' },
      { value: '서구' },
      { value: '유성구' },
      { value: '중구' }
    ]
  },
  {
    id: 8,
    name: '울산',
    list: [
      { value: '시/구/군' },
      { value: '남구' },
      { value: '동구' },
      { value: '북구' },
      { value: '중구' },
      { value: '울주군' }
    ]
  },
  {
    id: 9,
    name: '강원',
    list: [
      { value: '시/구/군' },
      { value: '강릉시' },
      { value: '동해시' },
      { value: '삼척시' },
      { value: '속초시' },
      { value: '원주시' },
      { value: '춘천시' },
      { value: '태백시' },
      { value: '고성군' },
      { value: '양구군' },
      { value: '양양군' },
      { value: '영월군' },
      { value: '인제군' },
      { value: '정선군' },
      { value: '철원군' },
      { value: '평창군' },
      { value: '홍천군' },
      { value: '화천군' },
      { value: '황성군' }
    ]
  },
  {
    id: 10,
    name: '세종',
    list: [
      { value: '시/구/군' },
      { value: '조치원읍' },
      { value: '연기면' },
      { value: '연동면' },
      { value: '부강면' },
      { value: '금남면' },
      { value: '장군면' },
      { value: '연서면' },
      { value: '전의면' },
      { value: '전동면' },
      { value: '소정면' },
      { value: '한솔동' },
      { value: '도담동' },
      { value: '아름동' },
      { value: '종촌동' },
      { value: '고운동' },
      { value: '보람동' },
      { value: '새롬동' },
      { value: '대평동' },
      { value: '소담동' },
      { value: '다정동' },
      { value: '해밀동' },
      { value: '반곡동' }
    ]
  },
  {
    id: 11,
    name: '충북',
    list: [
      { value: '시/구/군' },
      { value: '제천시' },
      { value: '청주시' },
      { value: '충주시' },
      { value: '괴산군' },
      { value: '단양군' },
      { value: '보은군' },
      { value: '영동군' },
      { value: '옥천군' },
      { value: '음성군' },
      { value: '진천군' },
      { value: '청원군' }
    ]
  },
  {
    id: 12,
    name: '충남',
    list: [
      { value: '시/구/군' },
      { value: '공주시' },
      { value: '보령시' },
      { value: '서산시' },
      { value: '아산시' },
      { value: '천안시' },
      { value: '금산군' },
      { value: '논산군' },
      { value: '당진군' },
      { value: '부여군' },
      { value: '서천군' },
      { value: '연기군' },
      { value: '예산군' },
      { value: '청양군' },
      { value: '태안군' },
      { value: '홍성군' }
    ]
  },
  {
    id: 13,
    name: '전북',
    list: [
      { value: '시/구/군' },
      { value: '군산시' },
      { value: '김제시' },
      { value: '남원시' },
      { value: '익산시' },
      { value: '전주시' },
      { value: '정읍시' },
      { value: '고창군' },
      { value: '무주군' },
      { value: '부안군' },
      { value: '순창군' },
      { value: '완주군' },
      { value: '임실군' },
      { value: '장수군' },
      { value: '진안군' }
    ]
  },
  {
    id: 14,
    name: '전남',
    list: [
      { value: '시/구/군' },
      { value: '광양시' },
      { value: '나주시' },
      { value: '목포시' },
      { value: '순천시' },
      { value: '여수시' },
      { value: '여천시' },
      { value: '강진군' },
      { value: '고흥군' },
      { value: '곡성군' },
      { value: '구례군' },
      { value: '담양군' },
      { value: '무안군' },
      { value: '보성군' },
      { value: '신안군' },
      { value: '여천군' },
      { value: '영광군' },
      { value: '영암군' },
      { value: '완도군' },
      { value: '장성군' },
      { value: '장흥군' },
      { value: '진도군' },
      { value: '함평군' },
      { value: '해남군' },
      { value: '화순군' }
    ]
  },
  {
    id: 15,
    name: '경북',
    list: [
      { value: '시/구/군' },
      { value: '경산시' },
      { value: '경주시' },
      { value: '구미시' },
      { value: '김천시' },
      { value: '문겅시' },
      { value: '상주시' },
      { value: '안동시' },
      { value: '영주시' },
      { value: '영천시' },
      { value: '포항시' },
      { value: '고령군' },
      { value: '군위군' },
      { value: '봉화군' },
      { value: '성주군' },
      { value: '영덕군' },
      { value: '영양군' },
      { value: '예천군' },
      { value: '울릉군' },
      { value: '울진군' },
      { value: '의성군' },
      { value: '청도군' },
      { value: '청송군' },
      { value: '칠곡군' }
    ]
  },
  {
    id: 16,
    name: '경남',
    list: [
      { value: '시/구/군' },
      { value: '거제시' },
      { value: '김해시' },
      { value: '마산시' },
      { value: '밀양시' },
      { value: '사천시' },
      { value: '울산시' },
      { value: '진주시' },
      { value: '진해시' },
      { value: '창원시' },
      { value: '통영시' },
      { value: '거창군' },
      { value: '고성군' },
      { value: '남해군' },
      { value: '산청군' },
      { value: '양산시' },
      { value: '의령군' },
      { value: '창녕군' },
      { value: '하동군' },
      { value: '함안군' },
      { value: '함양군' },
      { value: '합천군' }
    ]
  },
  {
    id: 17,
    name: '제주',
    list: [
      { value: '시/구/군' },
      { value: '서귀포시' },
      { value: '제주시' },
      { value: '남제주군' },
      { value: '북제주군' }
    ]
  }
]
